### PR TITLE
Upgrade the versions of Ruby and Bundler

### PR DESCRIPTION
**Pull request by universato**
### Description

Please see Issue #24

- Relevant Issues (required) : #24 
- Relevant PRs (optional) : nil
- Type of change :
  - [x] New feature
  - [x] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Comment by kojix2** [comment]
Hi. I forked to [sciruby-jp](https://github.com/sciruby-jp/networkx.rb) since there was no response. But I really don't want to do this. Can someone please merge it?

**Comment by Ashvith** [comment]
> Hi. I forked to [sciruby-jp](https://github.com/sciruby-jp/networkx.rb) since there was no response. But I really don't want to do this. Can someone please merge it?

Did you try asking out in the Matrix channel?

**Comment by kojix2** [comment]
Hi @Ashvith
What is Matrix channel?

**Comment by Ashvith** [comment]
@kojix2 [this](https://matrix.to/#/%23sciruby:matrix.org) is the link. Last time, around before GSoC 2021 was about to begin, I tried asking for some assistance in contributing to Numo-NArray, but since I did not see any proper response, I gave up.

**Comment by kojix2** [comment]
Thanks @Ashvith 
I did not know that.

**Pull request closed without merging**
