### PR TITLE
Rubocop offenses

### PR DESCRIPTION
**Pull request by arzoo14**
### Description

- Relevant Issues : #17 
- Relevant PRs : (optional)
- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [X] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

I have corrected 92 rubocop errors recently. Please review !

### CODE REVIEW

**Comment by npochhi** [comment]
@athityakumar, do we need to update gemspec? Travis is throwing an error because of the bundler version.

**Comment by npochhi** [comment]
@arzoo14, running rubocop on my laptop (on your branch, of course) gives a total of 171 rubocop errors, which I believe is the same as before. Resolving a complexity error would require much more than just adding a line break. You may try breaking the existing methods into smaller methods. Although, dividing the methods may result in the code being ugly, try to overcome that.

**Comment by arzoo14** [comment]
> @arzoo14, running rubocop on my laptop (on your branch, of course) gives a total of 171 rubocop errors, which I believe is the same as before. Resolving a complexity error would require much more than just adding a line break. You may try breaking the existing methods into smaller methods. Although, dividing the methods may result in the code being ugly, try to overcome that.

It was about 263 rubocop errors earlier and after correction, they have become 171. 
Yes, I'm working on complexity errors, I'll create a separate PR regarding that.

**Comment by npochhi** [comment]
Ah, that must be because my rubocop is yet to be updated.

**Comment by athityakumar** [comment]
@arzoo14 - Let me know if you're still working on fixing the complexity errors, or if we can keep that for a different PR.

**Comment by arzoo14** [comment]
@athityakumar 
I am super busy with my proposal these days. I'll fix the complexity errors as soon as possible and will create a new(different) PR regarding that.

**Pull request merged**
